### ISSUE TITLE
matlab 2019a 이후 버전에서 xlsread, xlswrite 권장하지 않음

### ISSUE THREAD

**Issue by gohoon** [oci-vip/scheduling#10]
다음 matlab 공식 도움말에 따라, 더이상 xlsread와 xlswrite사용을 권장하지 않음
[xlsread 도움말](https://kr.mathworks.com/help/matlab/ref/xlsread.html
)
[xlswrite 도움말](https://kr.mathworks.com/help/matlab/ref/xlswrite.html)

matlab 버전을 2019 이후 버전으로 업그레이드 하고
현재 xlsread와 xlswrite를 readmatrix 또는 writematrix로 변경할 것

**Comment by HJCho321** [comment]
금일 2019 이후 버전으로 업그레이드 진행하겠습니다

**Comment by gohoon** [comment]
코드 확인 및 실행 되는 것 확인했습니다.
