### ISSUE TITLE
윤달 계산하는 루틴 수정

### ISSUE THREAD

**Issue by gohoon** [oci-vip/scheduling#14]
for roop_y=1:1:Y %roop_y는 1년부터 year년까지 1씩 증가
    if ~(rem(roop_y,4)==0 && rem(roop_y,100)==0 || ~rem(roop_y,4)==0) %윤년은 1(참), 평년은 0(거짓)
        ed_month(2)=29; %윤년일 때 2월의 총 일수는 29일%
    else
        ed_month(2)=28; %평년일 때 2월의 총 일수는 28일%
    end
    total_d1(roop_y)=sum(ed_month); %total_d1은 year년 12월 31일까지의 총 일수
end

 현재 연도 y를 4로 나눈 나머지가 0이면 윤달,
 100으로 나눈 나머지가 0이면 평달,
 400 으로 나눈 나머지가 0이면 윤달 이에요

 for loop 으로 돌리지 말고 mod와 if로 변경 하세요

**Comment by HJCho321** [comment]
if mod(Y/4) == 0
    ed_month(2)=29;
else ed_month(2)=28;
end
total_d1(roop_y)=sum(ed_month)

다음과 같이 변경했습니다.
