### ISSUE TITLE
생산요청 ~ 생산반영 숫자 맞지않는 부분 확인

### ISSUE THREAD

**Issue by HJCho321** [oci-vip/scheduling#17]

**Comment by gohoon** [comment]
본인이 정한 제목이라 잘 알겠지만, 다른 사람들이 보면 무슨 말인지 알수있도록
설명을 화면과 함께 자세히 쓰세요

다음 그림과 같이, 두 번째 라인에 475x690x25 짜리 제품 8000 개를 2020년 5월 19일까지 만들어야 하는데,
스케줄러가 내놓은 것을 합산해보니 총 7582개만 생산하도록 스케줄링 되었습니다.
반드시 빠르게 수정되어야 할 부분 같습니다.

![image](https://user-images.githubusercontent.com/62731416/78414085-69599e00-7655-11ea-88f5-9c166190aef0.png)

**Comment by HJCho321** [comment]
#17 관련하여 요청수량만큼만 생산반영이 되게 수정하였습니다.

![요청수량,생산수량 일치화](https://user-images.githubusercontent.com/62861343/78753401-aead0100-79b0-11ea-94a5-932e904724d8.PNG)
