### ISSUE TITLE
4-1. 공휴일 및 휴일 생산가능 및 평일 생산불가일 적용  (~4/3)

### ISSUE THREAD

**Issue by HJCho321** [oci-vip/scheduling#2]
4-1. 공휴일 및 휴일 생산가능 적용
4-2. 특정 line 생산불가 적용
4-3. 휴일 생산가능 적용

**Comment by gohoon** [comment]
각각 분리

**Comment by gohoon** [comment]
현재  생산불가-및-가능 브랜치 실행해보면 다음과 같은 에러 메세지가 나옵니다.
![image](https://user-images.githubusercontent.com/62731416/78416340-1f77b480-7663-11ea-9993-1da3b5c81ea9.png)

행렬 만들때 차원이 안맞아서 생기는 오류 이므로 
다음과 같이 수정하였습니다.

![image](https://user-images.githubusercontent.com/62731416/78416353-36b6a200-7663-11ea-8e22-ce17ab03d6b1.png)

**Comment by gohoon** [comment]
1개 이상이 납기를 맞추지 못했다는 메세지는 왜 나오는거죠?

![image](https://user-images.githubusercontent.com/62731416/78416470-e1c75b80-7663-11ea-8ac7-3c37ff4aa020.png)

납기를 넘긴 제품이 없는데요?

![image](https://user-images.githubusercontent.com/62731416/78416484-f60b5880-7663-11ea-9547-b5f838248d0f.png)

**Comment by gohoon** [comment]
제가 이 메세지 찾으려고 코드 전체를 뒤져야 한다니 정말 말도 안되는 일입니다.

H_Production_complete_check  파일에 해당 메세지가 있더군요.

두 번 나오는 이유는  play.m에서 다음 그림과 같이 H파일을 두 번 부르기 때문인데요.
![image](https://user-images.githubusercontent.com/62731416/78416583-9d888b00-7664-11ea-9880-92c70a670c89.png)

첫번째 실행과 두 번째 실행 사이에서 뭔가 변수가 틀어졌기 때문일 것 같습니다
제가 찾아보도록 할께요

**Comment by gohoon** [comment]
4번째 제품이 납기여유일이 18일인데 생산완료일이 20일로 처리되서 
1개 이상 제품이 납기를 못맞췄다는 메세지가 나오고 있네요.

![image](https://user-images.githubusercontent.com/62731416/78416642-1be52d00-7665-11ea-8360-f78c964e42ef.png)

**Comment by gohoon** [comment]
우선, 현준씨가 엑셀 양식을 잘못만들었네요

다음 그림처럼 엑셀에서 납기를 입력할 때  Today() + 18 일 이렇게 수식을 입력해줬는데,
![image](https://user-images.githubusercontent.com/62731416/78416708-c65d5000-7665-11ea-9038-08044b9ab07a.png)

실제로 기준일은 2020-3-10이므로 Today()가 아니고 기준일이 적혀있는 셀을 참조했어야 합니다.
그래야 생산마감일이 잘 표시 되는 것 같습니다.

즉, 이번 이슈는 코드가 잘못된 것이 아니고
실제로 납기가 안맞는 상황이 벌어진 것이고,

엑셀에서 납기를 잘못 표기 했기 때문에, 납기를 넘어가는게 없다고 보였을 뿐인 상황입니다. 


그래서 두가지를 바꿨습니다.
1. 숨겨진 k열의 함수
![image](https://user-images.githubusercontent.com/62731416/78416765-41266b00-7666-11ea-8997-9a7133057f1e.png)

2. 그리고 M열의 함수
![image](https://user-images.githubusercontent.com/62731416/78416777-58655880-7666-11ea-8124-f1d64e95fdc4.png)


그래서 다음과 같이 결과를 표시해줍니다.

![image](https://user-images.githubusercontent.com/62731416/78416810-aaa67980-7666-11ea-8fbb-db70a97713dd.png)

**Comment by HJCho321** [comment]
아래 그림과 같이 주말 생산가능 및 주중 생산불가 logic을 적용시켰습니다.

![캡처](https://user-images.githubusercontent.com/62861343/78527032-cfd9ea00-7816-11ea-8936-138828a1df21.PNG)

**Comment by gohoon** [comment]
#26 완료
